### ISSUE TITLE
ionChange event documentation missing on ion-select

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1155] opened 2017-06-13 15:25 UTC
_From @gaurav-chandra on June 13, 2017 12:8_

https://ionicframework.com/docs/api/components/select/Select/

Output section is missing the documentation of ionChange event.

_Copied from original issue: ionic-team/ionic#12030_

**Comment by mhartington** [comment] 2017-06-13 15:28
Duplicate of https://github.com/ionic-team/ionic-site/issues/1145.

Classes that extend a base are not generating the docs

**Closed by mhartington** 2017-06-13 15:28 UTC
