### ISSUE TITLE
docs(navigation): what's the id of the root nav?

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1197] opened 2017-07-14 15:14 UTC
_From @peterpeterparker on July 14, 2017 7:53_

**Ionic version:**  (check one with "x")
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] support request (linked with https://forum.ionicframework.com/t/getrootnav-deprecated-use-getrootnavbyid-whats-the-value-of-the-root-nav-id)

**Current behavior:**
Following the introduction of Ionic 3.5.0, getRootNav was marked as deprecated. I would like to use then getRootNavById but I've got no idea what's the id of the root nav or how I could set my own id.

    (getRootNav) is deprecated and will be removed in the next major release. Use getRootNavById instead.

**Expected behavior:**
Document what's the root nav Id or how to set the root nav Id

**Steps to reproduce:**
- Update to ionic-angular >= 3.5.0
- Use getRootNav

**Other information:**

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Gulp CLI         : CLI version 1.2.2 Local version 3.9.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-gulp          : 1.0.2
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 5.2.0 

_Copied from original issue: ionic-team/ionic#12354_

**Comment by jgw96** [comment] 2017-07-14 15:15
_From @realtebo on July 14, 2017 9:15_

Same problem here. Near identical sistem configuration.
I'm using this function to force tabs to disappear when loggin out.

**Comment by epetre** [comment] 2017-07-14 15:18
Check the URL when running `ionic serve` if you don't have a split pane, I think you can use 'n4'
<img width="208" alt="ss" src="https://user-images.githubusercontent.com/1010282/28218118-88c736f2-6885-11e7-8f39-67073457f5a2.png">

or you can use ```this.app.getRootNavs()[0]```

**Comment by peterpeterparker** [comment] 2017-07-14 15:26
@epetre what's `n4`? how could you be sure it's a static value `n4`? where does that come from? does it gonna be the same in the future? It's a bit vague to just bet on it you know what I mean...

about `this.app.getRootNavs()[0]` I rather not do that to avoid any possible null pointer exception

**Comment by peterpeterparker** [comment] 2017-07-14 15:28
@jgw96 yes it's exactly the same issue, my bad I opened a duplicate  .... of my own issue. I should probably be a bit tired ;)

**Comment by epetre** [comment] 2017-07-14 22:59
Null pointer? If you don't have a root nav, your app is in a seriously messed up state 💣

**Comment by peterpeterparker** [comment] 2017-07-15 06:53
@epetre you never know ;)

**Comment by yanxiaodi** [comment] 2017-07-22 12:08
I have the same problem. I don't know how to get the Id of the Nav. It makes me confused. So I use this code:
`this.appCtrl.getRootNavs()[0].push(UserLoginPage);`
instead of `getRootNavById()` method.

In the `UserLoginPage`, I need to use `ion-toolbar` instead of `ion-navbar` to avoid user to navigate back to the last page.

**Comment by peterpeterparker** [comment] 2017-07-30 08:45
@jgw96 did your find something about this deprecation and more information about the id to use or how to set it?

**Comment by fiuzaB** [comment] 2017-10-21 00:06
@jgw96 , there will always be a root, right ? So couldn't we make it official to use the code suggested by @epetre  ?

**Comment by SamVerschueren** [comment] 2017-11-21 19:30
I dived into the code and found out the the `id` is set at [this line](https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller-base.ts#L106). As you can see, it looks far from static. The value `n4` seems to be coming back quite a lot, but to be honest, I don't want to use it as I don't want to suddenly break my application if on someones device the value turns out to be `n3` instead. I'm fine with deprecation, but at least provide developers with decent information on the alternatives. For now, I'm just keep using `getRootNav()`.

**Comment by ayakilani** [comment] 2017-11-23 11:05
Try :
this.appCtrl.getRootNavs()[0].setRoot('LoginPage');  
it's working for me !

**Comment by rajeevriitm** [comment] 2017-11-24 17:49
`getRootNavs()[0]` is essentially what `getRootNav()` does .

**Comment by SamVerschueren** [comment] 2017-11-28 16:10
The only thing `getRootNavs()[0]` does is remove the deprecation warning. Apparently Ionic wants to enforce the usage of `getRootNavById(id: string)` which is fine for me, but not if I'm not in charge of picking the id myself or explain how the id is derived.

**Comment by okonon** [comment] 2017-12-06 04:21
@jgw96 any advice how to proceed?

**Comment by karthikrp** [comment] 2017-12-21 09:32
+1

**Comment by siphiwe** [comment] 2017-12-31 15:39
Bump

**Comment by jordanpurinton** [comment] 2018-01-05 19:16
Bump

**Comment by koyadovic** [comment] 2018-01-12 16:58
Same here

**Comment by kingeke** [comment] 2018-01-27 13:37
no solution yet??

**Comment by okonon** [comment] 2018-01-27 18:40
Have not heard from Ionic team.

**Comment by jbarnabe** [comment] 2018-02-06 21:16
Same question :)

**Comment by lonwi** [comment] 2018-02-13 10:29
Any updates on this??

**Comment by epetre** [comment] 2018-02-13 13:32
You guys really need an official response for something that was answered in many ways in the past?

**Comment by fiuzaB** [comment] 2018-02-13 21:09
Sorry epetre. But I didn't find anything being said by the ionic team. If you did, would be great if you could share with us.

**Comment by mihirp1730** [comment] 2018-03-15 07:34
Got the warning.

> (getRootNav) is deprecated and will be removed in the next major release. Use getRootNavById instead.

Working for me. but the warning.
```
detailEvent(eventItem) {
    this.app.getRootNav().push(DetailEventsPage, { itemUp: eventItem });  
  }
```

I tried the lot on using **getRootNavById** but no result found.

there is no solution for this yet, I guess.

help me to remove the warning or guide me how to set Id.

**Comment by centos94** [comment] 2018-03-22 10:19
Hello there,
there are some things that aren't clear for me.

The problem is that **getRootNav** is deprecated, so it will be removed soon.
The console suggest to use **getRootNavById** instead, but isn't clear how to set a new root page from there and what id use.

It seems that the id is "n4" and we don't know why.
Some of you suggested to use
```
this.app.getRootNavs()[0].setRoot(LoginPage);
```

It works and there aren't warnings in console, but, will be deprecated also **getRootNavs**?

I also tried other ways and the following seems to work in the same way as the above one.
```
constructor(private app: MyApp, ...){}
...
this.app.rootPage = LoginPage;
```
**MyApp** is the class in file app.components.ts where i set up the initial page when the app starts.

I don't know what implications this could have, but for now it is another workaround at the problem.

Would be great if ionic team put some words on this with something official.

**Comment by carauzs** [comment] 2018-03-26 07:42
+1

**Comment by litchian18** [comment] 2018-04-25 01:58
@jgw96  please update this issue. Thanks

**Comment by mo7amd** [comment] 2018-06-10 07:16
any update about how we can get NavId ?

**Comment by JoseGeorges8** [comment] 2018-06-22 16:49
why making a getRootNavById if no documentation about this id will be provided? I'll just stick to getRootNav until it causes me problems

**Comment by jjvallesv** [comment] 2018-11-16 16:13
> Try :
> this.appCtrl.getRootNavs()[0].setRoot('LoginPage');
> it's working for me !

That's ok, but you need to remove the quotes of LoginPage:

this.app.getRootNavs()[0].setRoot(LoginPage);

**Comment by epetre** [comment] 2018-11-16 17:55
> Sorry epetre. But I didn't find anything being said by the ionic team. If you did, would be great if you could share with us.

They are missing some docs on how the nav works and how they are moving to supporting multiple navs by default, but looking at the code and interfaces was enough for me to assume that I should be using the navs how I mentioned above. I don't need more official github response than that and they don't seem to be elaborating on it anywhere...

**Comment by perrygovier** [comment] 2019-06-11 19:50
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs

**Closed by perrygovier** 2019-06-11 19:50 UTC
